#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Team:
#    path: /Team/
#    controller: App\Controller\DefaultController::Team

#Contact:
#    path: /Contact/
#    controller: App\Controller\DefaultController::Contact